# 2026-05-20 TIL — 이차보전 화면 엑셀 % 부풀림 해결, 그리드 셀별 첨부파일 업로드, 동일 기업 자동 복사 로직 설계

## 프로젝트 정보

| 항목 | 내용 |
|---|---|
| 프로젝트 | AraOn ERP (KOBC 차세대) |
| 담당자 | 최경민 |
| 작업 화면 | 이차보전 금액 검증내역 / 대출이자 지원사업 |
| 화면 ID | SFPS_CSBS018M / CWMI_SFCM201M |

---

## 오늘 작업 요약

1. 엑셀 다운로드 % 컬럼 부풀림 해결 — `excelCellType="text"` 속성으로 해결
2. 그리드 oneditend 분기 버그 분석 — OR/AND 조건 혼동 케이스
3. 그리드 셀별 첨부파일 업로드 구현 — `btn_addFile_onclick` + `callbackUploadDone`
4. 행추가 후 동일 기업 자동 복사 로직 설계 — `callbackClcmNm` 보강
5. 도움말 아이콘 헤더 핸들러 주석 정리

---

## [1] 엑셀 다운로드 % 컬럼 부풀림 (해결)

### 증상

같은 그리드 안 % 컬럼 2개 중 `intRto`만 엑셀 다운로드 시 ×100 부풀림.

| 컬럼 | DB raw | 화면 | 엑셀 |
|---|---|---|---|
| `assrRat` (보증요율) | 0.013 | 0.01% | 정상 |
| `intRto` (이차보전율) | 9.96 | 9.96% | **996.00%** |

### 원인

- 화면 `displayFormat="##.00%"`은 raw 값에 `%` 기호만 붙임 (×100 없음)
- 엑셀 다운로드 시 WebSquare가 셀에 백분율 서식을 박음
- 엑셀 백분율 서식 = raw에 ×100해서 표시
- `assrRat`는 raw가 소수(0.013)라 ×100 돼도 1.30%로 우연히 맞음
- `intRto`는 raw가 정수대(9.96)라 ×100 시 996.00%로 부풀림

### 해결

```xml
<w2:column id="intRto" excelCellType="text" ... />
```

`excelCellType="text"`로 엑셀 셀 타입을 텍스트 강제 → 백분율 서식 해석 차단 → 화면 표시값 그대로 박힘.

### 교훈

- `displayFormat`은 화면 렌더링용. 엑셀 다운로드는 별개 경로(셀 타입/서식 따로)
- 같은 displayFormat인데 한 컬럼만 깨질 때 = DB raw 스케일 불일치 + 엑셀 자동 서식 해석 콤보 의심

---

## [2] 그리드 oneditend / oncellclick 분기 버그 분석

### 증상 1: OR/AND 조건 혼동

```javascript
// 잘못된 코드 (3개 if 순차 = AND처럼 동작 → 항상 return)
if(this.getColumnIndex("rmmdFileGrpId") != col) return;
if(col != this.getColumnIndex("sprtTrgtEvdcPprsFileGrpId")) return;
if(col != this.getColumnIndex("loanNtshFileGrpId")) return;
```

col은 한 번에 단 하나 값이므로 3개 컬럼 모두에 동시 매칭 불가 → 무조건 어딘가에서 return.

**의도(OR) 수정안:**

```javascript
if(col != this.getColumnIndex("rmmdFileGrpId") 
&& col != this.getColumnIndex("sprtTrgtEvdcPprsFileGrpId") 
&& col != this.getColumnIndex("loanNtshFileGrpId")) {
    return;
}
```

### 증상 2: "통과한다" 오판

```javascript
console.log("col:", col);          // ← if 위에 있어서 무조건 찍힘
if(...) return;                    // ← 실제로 return 타고 있어도 위 로그는 보임
```

콘솔 로그가 if문 위에 있어서 "값이 정확히 찍히니까 통과한 거"로 오판. **진짜 통과 여부는 if 분기 안팎에 로그 박아 확인.**

### 교훈

- 콘솔 로그는 if문 **양쪽**에 박아야 분기 진단 정확
- 다중 조건 분기는 `||` / `&&` 의미 한 번 더 검토

---

## [3] 그리드 셀별 첨부파일 업로드 구현 (SFPS_CSBS018M)

### 요구사항

그리드 행의 4개 파일그룹ID 컬럼(`acinRpppFileGrpId`, `rmmdFileGrpId`, `sprtTrgtEvdcPprsFileGrpId`, `loanNtshFileGrpId`) 셀 클릭 시 파일 업로드 팝업 호출. 업로드 완료 후 짝이 되는 Nm 컬럼(`acinRpppFileNm`, `rmmdFileNm`, …)에 원본 파일명 바인딩.

### 핵심 패턴

#### A. 셀 클릭 → 컬럼 분기 + 컨텍스트 저장

```javascript
scwin.btn_addFile_onclick = function(row, col) {
    var idxAcin     = this.getColumnIndex("acinRpppFileGrpId");
    var idxRmmd     = this.getColumnIndex("rmmdFileGrpId");
    var idxSprt     = this.getColumnIndex("sprtTrgtEvdcPprsFileGrpId");
    var idxLoan     = this.getColumnIndex("loanNtshFileGrpId");
    
    var colId, nmColId;
    if(col === idxAcin)      { colId = "acinRpppFileGrpId";          nmColId = "acinRpppFileNm"; }
    else if(col === idxRmmd) { colId = "rmmdFileGrpId";              nmColId = "rmmdFileNm"; }
    else if(col === idxSprt) { colId = "sprtTrgtEvdcPprsFileGrpId";  nmColId = "sprtTrgtEvdcPprsFileNm"; }
    else if(col === idxLoan) { colId = "loanNtshFileGrpId";          nmColId = "loanNtshFileNm"; }
    else return;
    
    // 콜백에서 사용할 컨텍스트 저장
    scwin._uploadRow     = row;
    scwin._uploadColId   = colId;
    scwin._uploadNmColId = nmColId;
    
    var fileGrpId = dlt_loanIntSprtBizListVO.getCellData(row, colId);
    
    com.win.fn_fileUplodPop( fileGrpId
                          , 50
                          , ''
                          , ''
                          , 'scwin.callbackUploadDone');
};
```

#### B. 업로드 콜백 → 결과 바인딩

```javascript
scwin.callbackUploadDone = function(e) {
    var jsonD = e.retJson;
    if(!jsonD || !jsonD.length) return;
    
    var fileInfo = jsonD[0];
    var dl       = dlt_loanIntSprtBizListVO;
    var row      = scwin._uploadRow;
    
    dl.setCellData(row, scwin._uploadColId,   fileInfo.fileGrpId);
    dl.setCellData(row, scwin._uploadNmColId, fileInfo.fileOtxtNm);  // 원본명
};
```

### 트러블슈팅 기록

#### B-1. `dma_SbstSlipVO is not defined` 에러

기존 `callbackUploadDone`이 다른 화면 dataMap(`dma_SbstSlipVO`)을 참조하고 있어서 호출 즉시 ReferenceError. 콜백 전체를 위 코드로 교체하여 해결.

#### B-2. `result` 구조 확인

`e.retJson`은 배열. `e.retJson[0]`의 주요 키:

| 키 | 값 예시 | 비고 |
|---|---|---|
| `fileGrpId` | "" | 업로드 직후 빈값 (서버 저장 시 채번 추정) |
| `fileNm` | "20260521_3c4c4c46-…" | 서버 저장용 UUID |
| `fileOtxtNm` | "스크린샷 2026-04-07 160126.png" | 원본명 (화면 표시용) |
| `fileExtnNm` | "png" | |
| `fileSz` | 116730 | |
| `rowStatus` | "C" | |

**화면 표시는 `fileOtxtNm` 사용.**

#### B-3. uploadFileInfo 호출 payload의 `rfrn~` undefined

| payload | 값 |
|---|---|
| `Filename` | OK (파일명) |
| `FileData` | OK (바이너리) |
| `fileGrpId` | 빈값 (정상, 서버 채번 대기) |
| `imsiDir` | 빈값 |
| `rfrnDocId` / `rfrnColNm` / `rfrnTblNm` | **undefined** ← 미해결 |
| `callBackFunc` | OK |

**미해결:** `rfrn~` 3개가 undefined로 전송 중. `fn_fileUplodPop` 함수 시그니처에 6~8번째 인자가 있는지 확인 필요. 다른 화면 정상 호출부 보고 어떻게 채우는지 확인 필요.

### 핵심 패턴 메모

- **콜백 컨텍스트 보관**: `fn_fileUplodPop`이 콜백을 **문자열 이름**으로 받으므로 클로저 불가 → `scwin._uploadRow` 등 전역에 임시 저장 필요
- **`_` 접두사 컨벤션**: 내부용 임시 변수 표시
- **빈 `fileGrpId`는 정상**: 첫 업로드면 빈값 던지고 서버에서 채번 받아옴

---

## [4] 행추가 후 동일 기업 자동 복사 로직 (callbackClcmNm)

### 요구사항

1. 행추가 후 기업 검색
2. 동일 기업코드(`clcmNo`)를 가진 기존 row 존재 시:
   - 기업명 ~ 공사감면이자 컬럼 복사
   - 사업상태구분: 신규(31420001) → 연장(31420002) → 종료(31420003) 단계 증가
   - 진행상태구분: "진행"(31410001)으로 초기화

### 코드값 매핑

| 코드 | 의미 |
|---|---|
| `31410001` | 진행상태구분: 진행 |
| `31410002` | 진행상태구분: 종료 |
| `31420001` | 사업상태구분: 신규 |
| `31420002` | 사업상태구분: 연장 |
| `31420003` | 사업상태구분: 종료 |

### 구현안

```javascript
if(clcmNm === obj.clcmKornNm) {
    var dl = dlt_loanIntSprtBizListVO;
    var copyCols = ["기업명컬럼", "...", "공사감면이자컬럼"];  // 미확정
    var statusNext = {
        "31420001": "31420002",  // 신규 → 연장
        "31420002": "31420003"   // 연장 → 종료
    };
    
    for(var i = 0; i < dl.getRowCount(); i++) {
        if(i === rowIndex) continue;
        if(dl.getCellData(i, "clcmNo") !== obj.clcmNo) continue;
        
        for(var c = 0; c < copyCols.length; c++) {
            dl.setCellData(rowIndex, copyCols[c], dl.getCellData(i, copyCols[c]));
        }
        dl.setCellData(rowIndex, "bizStClssCd", statusNext[dl.getCellData(i, "bizStClssCd")] || "");
        dl.setCellData(rowIndex, "prgrsStClssCd", "31410001");
        break;
    }
}
```

### 미확정 사항

1. **복사 대상 컬럼 ID 리스트** — "기업명부터 공사감면이자까지" 정확한 컬럼 시퀀스 확인 필요
2. **요구사항의 "1차/2차"가 신규/연장 매핑 맞는지** — 사용자 표현(1차/2차)과 코드체계(신규/연장) 일치 여부 사수 확인 필요
3. **트리거 조건 `clcmNm === obj.clcmKornNm`** — 행추가 직후엔 빈값이라 항상 false일 가능성. 매칭은 `clcmNo` 기준으로 봐야 함

---

## [5] 도움말 아이콘 헤더 핸들러 주석 정리

### 헤더 클릭 시 팝업 토글

```javascript
/**
 * 그리드 헤더의 도움말("?") 아이콘 클릭 시 팝업 토글
 * - column49: 도움말 아이콘 전용 컬럼
 * - udc_help: 별도 absolute 배치된 팝업 컴포넌트
 */
scwin.grd_loanIntSprtBizListVO_onheaderclick = function(headerId) {
    if(headerId === "column49"){
        var btnColumn = this.dom.head_tds[9];           // 아이콘 컬럼
        var offsetLeft = btnColumn.offsetLeft - 30;     // 중앙 정렬 보정
        udc_help.setStyle("left", offsetLeft + "px");
        udc_help.childControlList.forEach(function(child){
            child.toggleClass("on");                    // 팝업 표시/숨김 토글
        })
    }
};
```

### 좌우 스크롤 시 위치 동기화

```javascript
/**
 * 좌우 스크롤 시 도움말 아이콘/팝업 위치 동기화 및 자동 숨김
 * - 대상 컬럼이 frozen 영역에 가려지면(25px 이하) 아이콘+팝업 숨김
 */
scwin.grd_loanIntSprtBizListVO_onscrollx = function() {
    var helpTargetColumn = this.dom.head_tds[8];   // 도움말 대상(선사분류)
    var btnColumn        = this.dom.head_tds[9];   // 아이콘 컬럼
    var offsetLeft       = btnColumn.offsetLeft - 30;
    udc_help.setStyle("left", offsetLeft + "px");
    
    if(helpTargetColumn.offsetWidth <= 25){
        btnColumn.classList.add("hideAfter");      // 아이콘 숨김
        udc_help.childControlList.forEach(function(child){
            child.removeClass("on");               // 팝업도 닫음
        })
    }else{
        btnColumn.classList.remove("hideAfter");
    }
};
```

---

## 잔여 작업 (다음 세션)

### 우선순위 높음

1. **첨부파일 업로드 `rfrn~` 인자 처리**
   - `fn_fileUplodPop` 함수 시그니처 확인 (Ctrl+H 검색)
   - 다른 정상 화면 호출부 참고
   - `rfrnTblNm` / `rfrnDocId` / `rfrnColNm` 채우기

2. **첨부파일 `fileGrpId` 채번 시점 확인**
   - 업로드 직후 빈값 → 저장 시 채번인지, 콜백에서 채워야 하는지

3. **행추가 동일 기업 복사 로직 마무리**
   - 복사 대상 컬럼 ID 리스트 확정
   - 트리거 조건 `clcmNm === obj.clcmKornNm` 재검토 (clcmNo 기준 매칭으로 변경)
   - 1차/2차 vs 신규/연장 매핑 사수 확인

### 미해결 이슈 (5/19 이월)

1. **`saveRepricingAplcn` 저장 로직 연결** (CWMI_SFCM201M)
   - 기존 INSERT 위치에서 Mapper 호출만 `updateRepricingAplcn`으로 교체
   - 시그니처 정합성 확인

2. **OB 날짜 변경 시 기준금리 부풀림 버그**
   - `selectCrtrInrt` 매퍼 SQL 확인
   - 281줄 `inrtClssCd` ← `cmptInrtClssCd` 매핑 검증
   - 279줄 `aplcnYmd` → `inrtCmptYmd` 의도 확인

3. **두 번째 탭 작은 그리드 퍼블**
   - content3 내부 `lybox > [ly_column, ly_column]` 구조 적용

### 코드 정리

- `debugger;` 라인 제거 (콜백/onclick 내)
- 잔존 콘솔 로그 정리

---

## 오늘의 핵심 교훈

| 구분 | 내용 |
|---|---|
| 엑셀 다운로드 | `displayFormat`은 화면용. 엑셀은 셀 타입/서식 별개 경로. `excelCellType` 활용 |
| 다중 if 분기 | 순차 if + return은 AND. OR 의도는 `&&` 묶음 한 번에 |
| 콘솔 로그 위치 | if문 위에 박으면 분기 결과 무관하게 찍힘. 양쪽에 박아야 진단 가능 |
| 콜백 컨텍스트 | 문자열 콜백명은 클로저 불가. `scwin._임시변수`로 우회 |
| 파일명 키 | `fileNm`(UUID) vs `fileOtxtNm`(원본). 화면 표시는 `fileOtxtNm` |
| 코드값 확인 | "1차/2차" 같은 사용자 표현을 코드체계와 매핑할 땐 사수 확인 필수 |
